import { PropsWithChildren } from 'react'
import { Poppins } from 'next/font/google'
import type { Metadata } from 'next'
import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Math',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={`${poppins.variable} font-poppins w-full`}>
      <body>{children}</body>
    </html>
  )
}
